In [1]:
# !conda install -c conda-forge pydotplus -y

In [2]:
!conda install -c conda-forge pydotplus -y

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.7.10

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.

In [3]:
# !conda install -c conda-forge python-graphviz -y

In [4]:
!conda install -c conda-forge python-graphviz -y

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.7.10

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/jupyterlab/conda/envs/python

  added / updated specs:
    - python-graphviz


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-graphviz-0.11.1     |             py_1          18 KB  conda-forge

The following NEW packages will be INSTALLED:

    python-graphviz: 0.11.1-py_1 conda-forge


Downloading and Extracting Packages
python-graphviz-0.11 | 18 KB     | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

In [6]:
# medical researcher compiling data for a study

# Import the Following Libraries:
import numpy as np 
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

# Downloading the Data
!wget -O drug200.csv https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/drug200.csv

# now, read data using pandas dataframe:    
my_data = pd.read_csv("drug200.csv", delimiter=",")
my_data[0:5]

# convert these features to numerical values. 
# pandas.get_dummies() Convert categorical variable into dummy/indicator variables.
# pd.get_dummies(my_data)

# About the dataset
# Imagine that you are a medical researcher compiling data for a study. You have collected data about a set of patients, all of whom suffered from the same illness. During their course of treatment, each patient responded to one of 5 medications, Drug A, Drug B, Drug c, Drug x and y. 
# Part of your job is to build a model to find out which drug might be appropriate for a future patient with the same illness. The feature sets of this dataset are Age, Sex, Blood Pressure, and Cholesterol of patients, and the target is the drug that each patient responded to. 
# It is a sample of binary classifier, and you can use the training part of the dataset to build a decision tree, and then use it to predict the class of a unknown patient, or to prescribe it to a new patient.

--2019-08-01 19:07:37--  https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/drug200.csv
Resolving s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)... 67.228.254.193
Connecting to s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)|67.228.254.193|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6027 (5.9K) [text/csv]
Saving to: ‘drug200.csv’

drug200.csv         100%[===================>]   5.89K  --.-KB/s    in 0s

2019-08-01 19:07:37 (150 MB/s) - ‘drug200.csv’ saved [6027/6027]

,Age,Na_to_K,Sex_F,Sex_M,BP_HIGH,BP_LOW,BP_NORMAL,Cholesterol_HIGH,Cholesterol_NORMAL,Drug_drugA,Drug_drugB,Drug_drugC,Drug_drugX,Drug_drugY
0,23,25.355,1,0,1,0,0,1,0,0,0,0,0,1
1,47,13.093,0,1,0,1,0,1,0,0,0,1,0,0
2,47,10.114,0,1,0,1,0,1,0,0,0,1,0,0
3,28,7.798,1,0,0,0,1,1,0,0,0,0,1,0
4,61,18.043,1,0,0,1,0,1,0,0,0,0,0,1
5,22,8.607,1,0,0,0,1,1,0,0,0,0,1,0
6,49,16.275,1,0,0,0,1,1,0,0,0,0,0,1
7,41,11.037,0,1,0,1,0,1,0,0,0,1,0,0
8,60,15.171,0,1,0,0,1,1,0,0,0,0,0,1
9,43,19.368,0,1,0,1,0,0,1,0,0,0,0,1
10,47,11.767,1,0,0,1,0,1,0,0,0,1,0,0
11,34,19.199,1,0,1,0,0,0,1,0,0,0,0,1
12,43,15.376,0,1,0,1,0,1,0,0,0,0,0,1
13,74,20.942,1,0,0,1,0,1,0,0,0,0,0,1
14,50,12.703,1,0,0,0,1,1,0,0,0,0,1,0
15,16,15.516,1,0,1,0,0,0,1,0,0,0,0,1
16,69,11.455,0,1,0,1,0,0,1,0,0,0,1,0
17,43,13.972,0,1,1,0,0,1,0,1,0,0,0,0
18,23,7.298,0,1,0,1,0,1,0,0,0,1,0,0
19,32,25.974,1,0,1,0,0,0,1,0,0,0,0,1
20,57,19.128,0,1,0,1,0,0,1,0,0,0,0,1
21,63,25.917,0,1,0,0,1,1,0,0,0,0,0,1
22,47,30.568,0,1,0,1,0,0,1,0,0,0,0,1
23,48,15.036,1,0,0,1,0,1,0,0,0,0,0,1
24,33,33.486,1,0,0,1,0,1,0,0,0,0,0,1
25,28,18.809,1,0,1,0,0,0,1,0,0,0,0,1
26,31,30.366,0,1,1,0,0,1,0,0,0,0,0,1
27,49,9.381,1,0,0,0,1,0,1,0,0,0,1,0
28,39,22.697,1,0,0,1,0,0,1,0,0,0,0,1
29,45,17.951,0,1,0,1,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,28,12.879,1,0,0,0,1,1,0,0,0,0,1,0
171,45,10.017,0,1,0,1,0,0,1,0,0,0,1,0
172,39,17.225,1,0,0,0,1,0,1,0,0,0,0,1
173,41,18.739,1,0,0,1,0,0,1,0,0,0,0,1
174,42,12.766,0,1,1,0,0,0,1,1,0,0,0,0
175,73,18.348,1,0,1,0,0,1,0,0,0,0,0,1
176,48,10.446,0,1,1,0,0,0,1,1,0,0,0,0
177,25,19.011,0,1,0,0,1,1,0,0,0,0,0,1
178,39,15.969,0,1,0,0,1,1,0,0,0,0,0,1
179,67,15.891,1,0,0,0,1,1,0,0,0,0,0,1
180,22,22.818,1,0,1,0,0,0,1,0,0,0,0,1
181,59,13.884,1,0,0,0,1,1,0,0,0,0,1,0
182,20,11.686,1,0,0,1,0,0,1,0,0,0,1,0
183,36,15.490,1,0,1,0,0,0,1,0,0,0,0,1
184,18,37.188,1,0,1,0,0,1,0,0,0,0,0,1
185,57,25.893,1,0,0,0,1,0,1,0,0,0,0,1
186,70,9.849,0,1,1,0,0,1,0,0,1,0,0,0
187,47,10.403,0,1,1,0,0,1,0,1,0,0,0,0
188,65,34.997,0,1,1,0,0,0,1,0,0,0,0,1
189,64,20.932,0,1,1,0,0,0,1,0,0,0,0,1
190,58,18.991,0,1,1,0,0,1,0,0,0,0,0,1
191,23,8.011,0,1,1,0,0,1,0,1,0,0,0,0
192,72,16.310,0,1,0,1,0,1,0,0,0,0,0,1
193,72,6.769,0,1,0,1,0,1,0,0,0,1,0,0
194,46,34.686,1,0,1,0,0,1,0,0,0,0,0,1
195,56,11.567,1,0,0,1,0,1,0,0,0,1,0,0
196,16,12.006,0,1,0,1,0,1,0,0,0,1,0,0
197,52,9.894,0,1,0,0,1,1,0,0,0,0,1,0
198,23,14.020,0,1,0,0,1,0,1,0,0,0,1,0
199,40,11.349,1,0,0,1,0,0,1,0,0,0,1,0